services:
 rh-service:
    build: .
    image: rh-service:latest
    container_name: rh-service-container
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - EUREKA_CLIENT=${EUREKA_CLIENT_URL}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_URL=${MYSQL_URL}
      - TOKEN=${TOKEN}
      - NAME=${NAME}
      - SECRET=${SECRET}
      - RH_SERVICE_PORT=${RH_SERVICE_PORT}
    networks:
      - microservices

networks:
  microservices:
    external: true
